FROM flwr/superexec:1.33.0

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN python -m pip install --no-cache-dir -r /app/requirements.txt

COPY clients.yml /app/clients.yml
COPY scripts/client_registration.py /app/scripts/client_registration.py

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "/app/scripts/client_registration.py"]
